import http.cookiejar as cookielib
from pathlib import Path
from typing import Optional
from urllib.parse import urlparse

from core.cookie_config import get_site_cookies_file_path
from utils.site_catalog import SiteCatalog


def _extract_host_from_url(target_url: str) -> Optional[str]:
    if not target_url:
        return None
    parsed = urlparse(target_url)
    host = parsed.hostname or ""
    if not host:
        return None
    return host.split(":", 1)[0].lstrip(".").lower()


def _iter_cookie_alias_matches(host: str):
    normalized_host = str(host or '').strip().lower()
    if not normalized_host:
        return

    try:
        catalog = SiteCatalog.get_catalog() or {}
    except Exception:
        catalog = {}

    for slug, entry in catalog.items():
        cookie_config = entry.get('cookie') or {}
        alias_domains = cookie_config.get('alias_domains') or []
        match_domain = str(cookie_config.get('match_domain') or '').strip().lower() or None
        for alias_domain in alias_domains:
            normalized_alias = str(alias_domain or '').strip().lstrip('.').lower()
            if not normalized_alias:
                continue
            if normalized_host == normalized_alias or normalized_host.endswith(f'.{normalized_alias}'):
                yield slug, match_domain


def resolve_cookie_file_for_url(target_url: str) -> Optional[str]:
    host = _extract_host_from_url(target_url)
    if not host:
        return None

    try:
        catalog = SiteCatalog.get_catalog() or {}
    except Exception:
        catalog = {}

    matched_site: Optional[str] = None
    for slug, entry in catalog.items():
        try:
            domains = [
                (d or "").strip().lstrip(".").lower()
                for d in entry.get("domains", [])
                if d
            ]
        except Exception:
            continue
        for d in domains:
            if host == d or host.endswith("." + d):
                matched_site = slug
                break
        if matched_site:
            break

    if not matched_site:
        matched_site = next((slug for slug, _match_domain in _iter_cookie_alias_matches(host)), None)

    if not matched_site:
        return None

    path = get_site_cookies_file_path(matched_site)
    if not path.exists():
        return None

    return str(path)


def _extract_top_level_domain_from_url(target_url: str) -> str:
    host = _extract_host_from_url(target_url) or ''
    parts = [part for part in host.split('.') if part]
    if len(parts) >= 2:
        return '.'.join(parts[-2:])
    return host


def resolve_cookie_match_domain_for_url(target_url: str) -> str:
    host = _extract_host_from_url(target_url) or ''
    for _slug, match_domain in _iter_cookie_alias_matches(host):
        if match_domain:
            return match_domain
    return _extract_top_level_domain_from_url(target_url)


def _read_cookie_file_as_query_string(path: Optional[str], target_url: str) -> str:
    if not path:
        return ''

    try:
        cookie_path = Path(path).expanduser()
    except Exception:
        return ''

    if not cookie_path.is_file():
        return ''

    jar = cookielib.MozillaCookieJar()

    try:
        jar.load(str(cookie_path), ignore_discard=True, ignore_expires=True)
    except Exception:
        return ''

    domain = resolve_cookie_match_domain_for_url(target_url)
    if not domain:
        return ''

    filtered = []
    for item in jar:
        try:
            if item.domain.endswith(domain):
                filtered.append(f'{item.name}={item.value}')
        except Exception:
            continue

    return '; '.join(filtered)


def filter_cookies_to_query_string(target_url: str) -> str:
    cookie_file = resolve_cookie_file_for_url(target_url)
    return _read_cookie_file_as_query_string(cookie_file, target_url)


def filter_cookies_to_query_string_by_domain(domain_or_url: str) -> str:
    if not domain_or_url:
        return ''

    target_url = domain_or_url
    if '://' not in target_url:
        target_url = f"https://{domain_or_url.lstrip('.')}"

    return filter_cookies_to_query_string(target_url)


def json_cookie_to_netscape(cookies: dict, domain_list: list, output_file):
    with open(output_file, 'w') as f:
        # 写入Netscape格式的文件头
        f.write("# Netscape HTTP Cookie File\n")
        f.write("# This file is generated by yt-dlp.  Do not edit.\n")
        f.write("\n")

        for site in cookies:
            match_domain = False
            if domain_list:
                for domain in domain_list:
                    if domain in site:
                        match_domain = True
                        break
            if domain_list and not match_domain:
                continue

            site_cookie = cookies[site]
            for cookie in site_cookie:

                if 'expirationDate' not in cookie or cookie['expirationDate'] == '' or cookie['expirationDate'] == 0:
                    continue
                domain = cookie['domain']
                if domain.startswith('.'):
                    domain = domain[1:]

                line = "\t".join([
                    domain,
                    str(cookie['httpOnly']),
                    cookie['path'],
                    str(cookie['secure']),
                    str(cookie['expirationDate']).split('.')[0],
                    cookie['name'],
                    cookie['value'],
                ])
                f.write(line + "\n")
