from typing import Optional

from crawl import (
    filter_cookies_to_query_string as sdk_filter_cookies_to_query_string,
    configure_cookie_file_resolver,
)
from core.cookie_config import get_cookies_file_path


def resolve_cookie_file_for_url(target_url: str) -> Optional[str]:
    try:
        file_path = get_cookies_file_path()
    except Exception:
        return None

    if not file_path:
        return None

    if not file_path.exists():
        return None

    return str(file_path)


configure_cookie_file_resolver(resolve_cookie_file_for_url)


def filter_cookies_to_query_string(target_url):
    return sdk_filter_cookies_to_query_string(target_url)


def filter_cookies_to_query_string_by_domain(domain_or_url):
    if not domain_or_url:
        return ""

    target_url = domain_or_url
    if "://" not in target_url:
        target_url = f"https://{domain_or_url.lstrip('.')}"

    return sdk_filter_cookies_to_query_string(target_url)


def json_cookie_to_netscape(cookies: dict, domain_list: list, output_file):
    with open(output_file, 'w') as f:
        # 写入Netscape格式的文件头
        f.write("# Netscape HTTP Cookie File\n")
        f.write("# This file is generated by yt-dlp.  Do not edit.\n")
        f.write("\n")

        for site in cookies:
            match_domain = False
            if domain_list:
                for domain in domain_list:
                    if domain in site:
                        match_domain = True
                        break
            if domain_list and not match_domain:
                continue

            site_cookie = cookies[site]
            for cookie in site_cookie:

                if 'expirationDate' not in cookie or cookie['expirationDate'] == '' or cookie['expirationDate'] == 0:
                    continue
                domain = cookie['domain']
                if domain.startswith('.'):
                    domain = domain[1:]

                line = "\t".join([
                    domain,
                    str(cookie['httpOnly']),
                    cookie['path'],
                    str(cookie['secure']),
                    str(cookie['expirationDate']).split('.')[0],
                    cookie['name'],
                    cookie['value'],
                ])
                f.write(line + "\n")
