[tool.ruff]
# 启用 pycodestyle (`E`) 和 Pyflakes (`F`) 规则
select = ["E", "F"]
# 忽略行太长的警告（E501）
ignore = ["E501"]

# 允许自动修复
fix = true

# 排除一些目录
exclude = [
    ".bzr",
    ".direnv",
    ".eggs",
    ".git",
    ".hg",
    ".mypy_cache",
    ".nox",
    ".pants.d",
    ".pytype",
    ".ruff_cache",
    ".svn",
    ".tox",
    ".venv",
    "__pypackages__",
    "_build",
    "buck-out",
    "build",
    "dist",
    "node_modules",
    "venv",
]

# 同样适用于 Python 文件
line-length = 120

# 允许使用未使用的变量，当它们以下划线开头时
dummy-variable-rgx = "^(_+|(_+[a-zA-Z0-9_]*[a-zA-Z0-9]+?))$"

# 目标 Python 版本
target-version = "py38"

[tool.ruff.mccabe]
# 不像 Flake8，默认启用 McCabe 复杂性检查
max-complexity = 10