import type { Component } from 'vue'
import {
  AlertCircle,
  AlertTriangle,
  ArrowLeft,
  Bell,
  Bolt,
  Box,
  Bookmark,
  BookmarkCheck,
  BookmarkPlus,
  Check,
  CheckCircle2,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  Clipboard,
  Circle,
  CirclePlay,
  Clapperboard,
  Clock,
  Copy,
  Cookie,
  Cpu,
  Download,
  Eye,
  EyeOff,
  ExternalLink,
  FileText,
  Film,
  Funnel,
  Globe,
  Gauge,
  GripHorizontal,
  GripVertical,
  Heart,
  History,
  Home,
  ImageOff,
  Inbox,
  Info,
  KeyRound,
  LayoutGrid,
  Library,
  List,
  ListMusic,
  ListVideo,
  ListPlus,
  Loader2,
  LoaderCircle,
  Link,
  LogOut,
  Maximize,
  Minimize,
  Monitor,
  Moon,
  MoreHorizontal,
  Minus,
  Network,
  PanelRightOpen,
  Palette,
  Pause,
  Pencil,
  PictureInPicture,
  PictureInPicture2,
  Play,
  PlayCircle,
  Plus,
  PlusCircle,
  Puzzle,
  RefreshCw,
  Repeat,
  RotateCcw,
  RotateCw,
  Scissors,
  Search,
  Settings,
  Settings2,
  Share2,
  ShieldAlert,
  ShieldCheck,
  Shuffle,
  SkipBack,
  SkipForward,
  Square,
  Star,
  Subtitles,
  Sun,
  ThumbsDown,
  ThumbsUp,
  Trash2,
  TvMinimal,
  TvMinimalPlay,
  Upload,
  User,
  Unlink,
  Volume1,
  Volume2,
  VolumeOff,
  VolumeX,
  X,
  XCircle,
  Zap,
  CaptionsOff,
  BadgeCheck,
} from 'lucide-vue-next'

export const APP_ICON_MAP = {
  addToPlaylist: ListPlus,
  alert: AlertTriangle,
  appearance: Palette,
  autoplayNext: CirclePlay,
  back: ArrowLeft,
  bolt: Bolt,
  bookmark: Bookmark,
  brand: Zap,
  breadcrumb: ChevronRight,
  chevronDown: ChevronDown,
  chevronLeft: ChevronLeft,
  chevronRight: ChevronRight,
  chevronUp: ChevronUp,
  check: Check,
  clipboard: Clipboard,
  clip: Scissors,
  close: X,
  circle: Circle,
  content: ShieldCheck,
  cookie: Cookie,
  cube: Box,
  dislike: ThumbsDown,
  download: Download,
  error: AlertCircle,
  eye: Eye,
  eyeOff: EyeOff,
  externalLink: ExternalLink,
  film: Film,
  filter: Funnel,
  fullscreen: Maximize,
  fullscreenExit: Minimize,
  gripHorizontal: GripHorizontal,
  gripVertical: GripVertical,
  heart: Heart,
  history: History,
  home: Home,
  imageOff: ImageOff,
  inbox: Inbox,
  info: Info,
  like: ThumbsUp,
  layoutGrid: LayoutGrid,
  library: Library,
  list: List,
  loading: LoaderCircle,
  loadingSpinner: Loader2,
  link: Link,
  logout: LogOut,
  logs: FileText,
  loop: Repeat,
  markClip: Clapperboard,
  maximizeWindow: Square,
  minimizeWindow: Minus,
  more: MoreHorizontal,
  next: SkipForward,
  notification: Bell,
  pause: Pause,
  panelOpen: PanelRightOpen,
  pip: PictureInPicture2,
  pipExit: PictureInPicture,
  playback: PlayCircle,
  play: Play,
  playlistMusic: ListMusic,
  playlistVideo: ListVideo,
  playlists: List,
  plusCircle: PlusCircle,
  plugins: Puzzle,
  plus: Plus,
  previous: SkipBack,
  pencil: Pencil,
  quality: BadgeCheck,
  refresh: RefreshCw,
  replay: RotateCcw,
  rotate: RotateCw,
  restoreWindow: Copy,
  scheduledTasks: Cpu,
  security: KeyRound,
  securityAlert: ShieldAlert,
  server: Network,
  settingsNav: Settings2,
  settingsPanel: Settings,
  share: Share2,
  shuffle: Shuffle,
  siteFallback: Globe,
  skipBackward: SkipBack,
  skipForward: SkipForward,
  search: Search,
  speed: Gauge,
  star: Star,
  statusSuccess: CheckCircle2,
  stop: Square,
  subscriptions: Bookmark,
  subtitles: Subtitles,
  subtitlesOff: CaptionsOff,
  sync: RefreshCw,
  time: Clock,
  themeDark: Moon,
  themeLight: Sun,
  themeSystem: Monitor,
  trash: Trash2,
  upload: Upload,
  unlink: Unlink,
  user: User,
  volumeHigh: Volume2,
  volumeLow: Volume1,
  volumeMute: VolumeX,
  volumeOff: VolumeOff,
  warning: AlertCircle,
  watchLater: BookmarkPlus,
  watchLaterActive: BookmarkCheck,
  widescreen: TvMinimalPlay,
  widescreenExit: TvMinimal,
  xCircle: XCircle,
} as const

export type AppIconName = keyof typeof APP_ICON_MAP

export function resolveAppIcon(name: AppIconName): Component {
  return APP_ICON_MAP[name]
}
