SYNC_DASHBOARD_FEED_CHANNEL = 'squirrel:sync-center:feed'
SYNC_DASHBOARD_EXTRACT_CHANNEL = 'squirrel:sync-center:extract'
SYNC_DASHBOARD_RUN_CHANNEL = 'squirrel:sync-center:run'
SYNC_DASHBOARD_HEARTBEAT_INTERVAL_SECONDS = 15
SYNC_DASHBOARD_PUBSUB_TIMEOUT_SECONDS = 1.0
