"""add channel table index

Revision ID: e96836d5920a
Revises: 259a103b130f
Create Date: 2024-12-07 12:02:14.776576

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = 'e96836d5920a'
down_revision = '259a103b130f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_channel_name', 'channel', ['name'], unique=False)
    op.create_index(op.f('ix_channel_channel_id'), 'channel', ['channel_id'], unique=False)
    op.create_index(op.f('ix_channel_created_at'), 'channel', ['created_at'], unique=False)
    op.create_index('idx_channel_video_channel_uploaded', 'channel_video', ['channel_id', 'uploaded_at'], unique=False)
    op.create_index('idx_channel_video_read_status', 'channel_video', ['channel_id', 'if_read'], unique=False)
    op.create_index(op.f('ix_channel_video_channel_id'), 'channel_video', ['channel_id'], unique=False)
    op.create_index(op.f('ix_channel_video_uploaded_at'), 'channel_video', ['uploaded_at'], unique=False)
    op.create_index(op.f('ix_channel_video_video_id'), 'channel_video', ['video_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_channel_video_video_id'), table_name='channel_video')
    op.drop_index(op.f('ix_channel_video_uploaded_at'), table_name='channel_video')
    op.drop_index(op.f('ix_channel_video_channel_id'), table_name='channel_video')
    op.drop_index('idx_channel_video_read_status', table_name='channel_video')
    op.drop_index('idx_channel_video_channel_uploaded', table_name='channel_video')
    op.drop_index(op.f('ix_channel_created_at'), table_name='channel')
    op.drop_index(op.f('ix_channel_channel_id'), table_name='channel')
    op.drop_index('idx_channel_name', table_name='channel')
    # ### end Alembic commands ###
