"""add like video feature

Revision ID: 22d7cb2529de
Revises: 43d8096de989
Create Date: 2024-12-01 19:30:48.623387

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '22d7cb2529de'
down_revision = '43d8096de989'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('channel_video', sa.Column('is_liked', sa.Integer(), nullable=True))
    op.drop_column('channel_video', 'is_disliked')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('channel_video', sa.Column('is_disliked', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.drop_column('channel_video', 'is_liked')
    # ### end Alembic commands ###
