"""add_metric_snapshot_table

Revision ID: 25928e33059b
Revises: 55f4f8e7e7fa
Create Date: 2025-12-07 21:09:32.189746

"""
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision = "25928e33059b"
down_revision = "55f4f8e7e7fa"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table("metric_snapshot",
    sa.Column("id", sa.Integer(), nullable=False),
    sa.Column("metric_name", sa.VARCHAR(length=128), nullable=False),
    sa.Column("metric_type", sa.VARCHAR(length=32), nullable=False),
    sa.Column("labels", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column("value", sa.DECIMAL(precision=20, scale=6), nullable=False),
    sa.Column("timestamp", sa.DateTime(), nullable=False),
    sa.Column("created_at", sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_metric_labels", "metric_snapshot", ["labels"], unique=False, postgresql_using="gin")
    op.create_index("ix_metric_name_timestamp", "metric_snapshot", ["metric_name", "timestamp"], unique=False)
    op.create_index(op.f("ix_metric_snapshot_timestamp"), "metric_snapshot", ["timestamp"], unique=False)
    op.create_index("ix_metric_timestamp", "metric_snapshot", ["timestamp"], unique=False)
    op.create_index("ix_metric_type", "metric_snapshot", ["metric_type"], unique=False)
    op.drop_index(op.f("ix_progress_created_at"), table_name="progress_record")
    op.drop_index(op.f("ix_progress_event_type"), table_name="progress_record")
    op.drop_index(op.f("ix_progress_subscription_id"), table_name="progress_record")
    op.drop_index(op.f("ix_progress_trace_id"), table_name="progress_record")
    op.drop_table("progress_record")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table("progress_record",
    sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column("event_type", sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column("trace_id", sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column("subscription_id", sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column("video_id", sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column("url", sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.Column("current_count", sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column("total_count", sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column("progress_percentage", sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=False),
    sa.Column("message", sa.VARCHAR(length=512), autoincrement=False, nullable=True),
    sa.Column("error_message", sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column("created_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint("id", name=op.f("progress_record_pkey")),
    )
    op.create_index(op.f("ix_progress_trace_id"), "progress_record", ["trace_id"], unique=False)
    op.create_index(op.f("ix_progress_subscription_id"), "progress_record", ["subscription_id"], unique=False)
    op.create_index(op.f("ix_progress_event_type"), "progress_record", ["event_type"], unique=False)
    op.create_index(op.f("ix_progress_created_at"), "progress_record", ["created_at"], unique=False)
    op.drop_index("ix_metric_type", table_name="metric_snapshot")
    op.drop_index("ix_metric_timestamp", table_name="metric_snapshot")
    op.drop_index(op.f("ix_metric_snapshot_timestamp"), table_name="metric_snapshot")
    op.drop_index("ix_metric_name_timestamp", table_name="metric_snapshot")
    op.drop_index("ix_metric_labels", table_name="metric_snapshot", postgresql_using="gin")
    op.drop_table("metric_snapshot")
    # ### end Alembic commands ###
