"""alter channel video title column length

Revision ID: 259a103b130f
Revises: 22d7cb2529de
Create Date: 2024-12-04 22:01:50.399855

"""
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '259a103b130f'
down_revision = '22d7cb2529de'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('channel_video', 'title',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255),
               type_=mysql.VARCHAR(length=1024),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('channel_video', 'title',
               existing_type=mysql.VARCHAR(length=1024),
               type_=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255),
               existing_nullable=True)
    # ### end Alembic commands ###
