"""alter video_history add user_id column

Revision ID: 26a66d226ef6
Revises: 47d1e4b46f5a
Create Date: 2025-02-16 18:09:07.995996

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '26a66d226ef6'
down_revision = '47d1e4b46f5a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('video_history', sa.Column('user_id', sa.Integer(), nullable=False))
    op.add_column('video_history', sa.Column('start_time', sa.DateTime(), nullable=False))
    op.add_column('video_history', sa.Column('end_time', sa.DateTime(), nullable=False))
    op.add_column('video_history', sa.Column('duration', sa.Float(), nullable=False))
    op.alter_column('video_history', 'last_position',
               existing_type=mysql.INTEGER(),
               type_=sa.Float(),
               existing_nullable=False)
    op.create_index(op.f('ix_video_history_user_id'), 'video_history', ['user_id'], unique=False)
    op.drop_column('video_history', 'total_duration')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('video_history', sa.Column('total_duration', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_video_history_user_id'), table_name='video_history')
    op.alter_column('video_history', 'last_position',
               existing_type=sa.Float(),
               type_=mysql.INTEGER(),
               existing_nullable=False)
    op.drop_column('video_history', 'duration')
    op.drop_column('video_history', 'end_time')
    op.drop_column('video_history', 'start_time')
    op.drop_column('video_history', 'user_id')
    # ### end Alembic commands ###
