"""remove user subscirption is_extract_all column

Revision ID: 349698b1daa9
Revises: c2776fd2f44a
Create Date: 2025-02-05 20:08:43.322317

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '349698b1daa9'
down_revision = 'c2776fd2f44a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_subscription', 'is_extract_all')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_subscription', sa.Column('is_extract_all', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
