"""add_indexes_video_interaction

Revision ID: 38275161e059
Revises: 979c773ed34a
Create Date: 2025-10-05 10:59:25.806385

"""


# revision identifiers, used by Alembic.
revision = "38275161e059"
down_revision = "979c773ed34a"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
