"""add_scheduler_status_table

Revision ID: 41788451930b
Revises: a6af4b319ee1
Create Date: 2026-01-03 21:05:53.649692

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '41788451930b'
down_revision = 'a6af4b319ee1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scheduler_status',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('process_name', sa.VARCHAR(length=50), nullable=False, comment='进程名称'),
    sa.Column('is_running', sa.Boolean(), nullable=False, comment='是否运行中'),
    sa.Column('job_count', sa.Integer(), nullable=False, comment='任务数量'),
    sa.Column('last_heartbeat', sa.DateTime(), nullable=False, comment='最后心跳时间'),
    sa.Column('started_at', sa.DateTime(), nullable=True, comment='启动时间'),
    sa.Column('stopped_at', sa.DateTime(), nullable=True, comment='停止时间'),
    sa.Column('error_message', sa.TEXT(), nullable=True, comment='错误信息'),
    sa.Column('legacy_tasks', sa.JSON(), nullable=False, server_default='{}', comment='传统任务信息'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('process_name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('scheduler_status')
    # ### end Alembic commands ###
