"""add unique index for video url

Revision ID: 55f4f8e7e7fa
Revises: 38275161e059
Create Date: 2025-11-30 14:17:05.921018

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '55f4f8e7e7fa'
down_revision = '38275161e059'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ux_video_url', 'video', ['url'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ux_video_url', table_name='video')
    # ### end Alembic commands ###
