"""add index

Revision ID: 5f7fdecef704
Revises: 9313ee0fab95
Create Date: 2025-08-03 15:36:55.025235

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5f7fdecef704'
down_revision = '9313ee0fab95'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_subscription_is_deleted', 'subscription', ['is_deleted'], unique=False)
    op.create_index('ix_subscription_type', 'subscription', ['type'], unique=False)
    op.create_index('ix_subscription_video_subscription_id', 'subscription_video', ['subscription_id'], unique=False)
    op.create_index('ix_subscription_video_video_id', 'subscription_video', ['video_id'], unique=False)
    op.create_index('ix_user_subscription_is_deleted', 'user_subscription', ['is_deleted'], unique=False)
    op.create_index('ix_user_subscription_subscription_id', 'user_subscription', ['subscription_id'], unique=False)
    op.create_index('ix_user_subscription_user_id', 'user_subscription', ['user_id'], unique=False)
    op.create_index('ix_video_is_deleted', 'video', ['is_deleted'], unique=False)
    op.create_index('ix_video_publish_date', 'video', ['publish_date'], unique=False)
    op.create_index('ix_video_title', 'video', ['title'], unique=False)
    op.create_index('ix_video_history_user_video', 'video_history', ['user_id', 'video_id'], unique=False)
    op.create_index('ix_video_history_video_id', 'video_history', ['video_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_video_history_video_id', table_name='video_history')
    op.drop_index('ix_video_history_user_video', table_name='video_history')
    op.drop_index('ix_video_title', table_name='video')
    op.drop_index('ix_video_publish_date', table_name='video')
    op.drop_index('ix_video_is_deleted', table_name='video')
    op.drop_index('ix_user_subscription_user_id', table_name='user_subscription')
    op.drop_index('ix_user_subscription_subscription_id', table_name='user_subscription')
    op.drop_index('ix_user_subscription_is_deleted', table_name='user_subscription')
    op.drop_index('ix_subscription_video_video_id', table_name='subscription_video')
    op.drop_index('ix_subscription_video_subscription_id', table_name='subscription_video')
    op.drop_index('ix_subscription_type', table_name='subscription')
    op.drop_index('ix_subscription_is_deleted', table_name='subscription')
    # ### end Alembic commands ###
