"""add logic delete column

Revision ID: 657baf9bdeb6
Revises: ab90b7f67bb8
Create Date: 2024-12-14 20:43:31.241977

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '657baf9bdeb6'
down_revision = 'ab90b7f67bb8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('creator', sa.Column('is_deleted', sa.Boolean(), nullable=False))
    op.add_column('subscription', sa.Column('is_deleted', sa.Boolean(), nullable=False))
    op.add_column('video', sa.Column('is_deleted', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('video', 'is_deleted')
    op.drop_column('subscription', 'is_deleted')
    op.drop_column('creator', 'is_deleted')
    # ### end Alembic commands ###
