"""alter subscription table column name

Revision ID: 6ae10dd860f7
Revises: bfc975377fe7
Create Date: 2025-01-19 13:50:00.828469

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6ae10dd860f7'
down_revision = 'bfc975377fe7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('subscription', 'content_type', new_column_name='type',
                    existing_type=sa.VARCHAR(length=32))
    op.alter_column('subscription', 'content_name', new_column_name='name',
                    existing_type=sa.VARCHAR(length=128))
    op.alter_column('subscription', 'content_url', new_column_name='url',
                    existing_type=sa.VARCHAR(length=2048))
    op.alter_column('subscription', 'avatar_url', new_column_name='avatar',
                    existing_type=sa.VARCHAR(length=2048))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('subscription', 'type', new_column_name='content_type',
                    existing_type=sa.VARCHAR(length=32))
    op.alter_column('subscription', 'name', new_column_name='content_name',
                    existing_type=sa.VARCHAR(length=128))
    op.alter_column('subscription', 'url', new_column_name='content_url',
                    existing_type=sa.VARCHAR(length=2048))
    op.alter_column('subscription', 'avatar', new_column_name='avatar_url',
                    existing_type=sa.VARCHAR(length=2048))
    # ### end Alembic commands ###
