"""add_video_creator_indexes_for_performance

Revision ID: 6f204e073323
Revises: d20b9a4d9bdd
Create Date: 2025-10-04 22:55:33.253356

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6f204e073323'
down_revision = 'd20b9a4d9bdd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_video_creator_creator_id', 'video_creator', ['creator_id'], unique=False)
    op.create_index('ix_video_creator_video_id', 'video_creator', ['video_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_video_creator_video_id', table_name='video_creator')
    op.drop_index('ix_video_creator_creator_id', table_name='video_creator')
    # ### end Alembic commands ###
