"""alter subscription config

Revision ID: 71e7bb6d6875
Revises: 75367636201d
Create Date: 2025-01-26 23:50:49.784087

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '71e7bb6d6875'
down_revision = '75367636201d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subscription', 'is_auto_download')
    op.drop_column('subscription', 'is_extract_all')
    op.drop_column('subscription', 'is_download_all')
    op.add_column('user_subscription', sa.Column('is_enable', sa.Boolean(), nullable=False))
    op.add_column('user_subscription', sa.Column('is_auto_download', sa.Boolean(), nullable=False))
    op.add_column('user_subscription', sa.Column('is_download_all', sa.Boolean(), nullable=False))
    op.add_column('user_subscription', sa.Column('is_extract_all', sa.Boolean(), nullable=False))
    op.add_column('user_subscription', sa.Column('is_deleted', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_subscription', 'is_deleted')
    op.drop_column('user_subscription', 'is_extract_all')
    op.drop_column('user_subscription', 'is_download_all')
    op.drop_column('user_subscription', 'is_auto_download')
    op.drop_column('user_subscription', 'is_enable')
    op.add_column('subscription', sa.Column('is_download_all', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False))
    op.add_column('subscription', sa.Column('is_extract_all', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False))
    op.add_column('subscription', sa.Column('is_auto_download', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
