"""init table

Revision ID: 7a101523feb2
Revises:
Create Date: 2025-08-06 00:52:30.031871

"""

import sqlalchemy as sa
from sqlalchemy.dialects import mysql

from alembic import op

# revision identifiers, used by Alembic.
revision = '7a101523feb2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'account',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('account_type', sa.VARCHAR(length=20), nullable=False),
        sa.Column('identifier', sa.VARCHAR(length=120), nullable=False),
        sa.Column('credential', sa.VARCHAR(length=128), nullable=False),
        sa.Column('is_verified', sa.Boolean(), nullable=False),
        sa.Column('last_login_at', sa.DateTime(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('identifier'),
    )
    op.create_table(
        'creator',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.VARCHAR(length=128), nullable=True),
        sa.Column('url', sa.VARCHAR(length=2048), nullable=False),
        sa.Column('avatar', sa.VARCHAR(length=2048), nullable=True),
        sa.Column('description', sa.Text(), nullable=True),
        sa.Column('is_deleted', sa.Boolean(), nullable=False),
        sa.Column('extra_data', sa.JSON(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_table(
        'download_task',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('video_id', sa.Integer(), nullable=False),
        sa.Column('status', mysql.VARCHAR(length=32), nullable=False),
        sa.Column('downloaded_size', sa.BigInteger(), nullable=True),
        sa.Column('total_size', sa.BigInteger(), nullable=True),
        sa.Column('speed', mysql.VARCHAR(length=255), nullable=True),
        sa.Column('eta', mysql.VARCHAR(length=32), nullable=True),
        sa.Column('percent', mysql.VARCHAR(length=32), nullable=True),
        sa.Column('retry', sa.Integer(), nullable=False),
        sa.Column('error_message', sa.Text(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_table(
        'external_request_log',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('url', sa.Text(), nullable=False),
        sa.Column('domain', sa.String(length=255), nullable=False),
        sa.Column('method', sa.String(length=10), nullable=False),
        sa.Column('params', sa.Text(), nullable=True),
        sa.Column('body', sa.Text(), nullable=True),
        sa.Column('size', sa.Integer(), nullable=False),
        sa.Column('status_code', sa.Integer(), nullable=False),
        sa.Column('duration', sa.Float(), nullable=False),
        sa.Column('error', sa.Text(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_table(
        'message',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('body', sa.Text(), nullable=False),
        sa.Column('send_status', sa.VARCHAR(length=32), nullable=False),
        sa.Column('retry_count', sa.Integer(), nullable=False),
        sa.Column('next_retry_time', sa.DateTime(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_table(
        'podcast_channels',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('title', sa.VARCHAR(length=128), nullable=False),
        sa.Column('description', sa.Text(), nullable=True),
        sa.Column('author', sa.VARCHAR(length=128), nullable=True),
        sa.Column('cover_url', sa.VARCHAR(length=2048), nullable=True),
        sa.Column('rss_url', sa.VARCHAR(length=2048), nullable=False),
        sa.Column('website_url', sa.VARCHAR(length=2048), nullable=True),
        sa.Column('language', sa.VARCHAR(length=32), nullable=True),
        sa.Column('categories', sa.VARCHAR(length=32), nullable=True),
        sa.Column('last_updated', sa.DateTime(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(op.f('ix_podcast_channels_title'), 'podcast_channels', ['title'], unique=False)
    op.create_table(
        'podcast_episodes',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('channel_id', sa.Integer(), nullable=False),
        sa.Column('title', sa.VARCHAR(length=128), nullable=False),
        sa.Column('description', sa.Text(), nullable=True),
        sa.Column('audio_url', sa.VARCHAR(length=2048), nullable=False),
        sa.Column('duration', sa.Integer(), nullable=True),
        sa.Column('published_at', sa.DateTime(), nullable=True),
        sa.Column('cover_url', sa.VARCHAR(length=2048), nullable=True),
        sa.Column('is_read', sa.Boolean(), nullable=False),
        sa.Column('last_position', sa.Integer(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(op.f('ix_podcast_episodes_title'), 'podcast_episodes', ['title'], unique=False)
    op.create_table(
        'podcast_play_history',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('episode_id', sa.Integer(), nullable=False),
        sa.Column('position', sa.Integer(), nullable=False),
        sa.Column('duration', sa.Integer(), nullable=False),
        sa.Column('last_played_at', sa.DateTime(), nullable=False),
        sa.Column('is_finished', sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_table(
        'podcast_subscriptions',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('channel_id', sa.Integer(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_table(
        'subscription',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('type', sa.VARCHAR(length=32), nullable=False),
        sa.Column('name', sa.VARCHAR(length=128), nullable=False),
        sa.Column('url', sa.VARCHAR(length=2048), nullable=True),
        sa.Column('avatar', sa.VARCHAR(length=2048), nullable=True),
        sa.Column('description', sa.Text(), nullable=True),
        sa.Column('total_videos', sa.Integer(), nullable=False),
        sa.Column('is_deleted', sa.Boolean(), nullable=False),
        sa.Column('extra_data', sa.JSON(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index('ix_subscription_is_deleted', 'subscription', ['is_deleted'], unique=False)
    op.create_index('ix_subscription_type', 'subscription', ['type'], unique=False)
    op.create_table(
        'subscription_video',
        sa.Column('subscription_id', sa.Integer(), nullable=False),
        sa.Column('video_id', sa.Integer(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint('subscription_id', 'video_id'),
    )
    op.create_index('ix_subscription_video_subscription_id', 'subscription_video', ['subscription_id'], unique=False)
    op.create_index('ix_subscription_video_video_id', 'subscription_video', ['video_id'], unique=False)
    op.create_table(
        'system_config',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('key', sa.VARCHAR(length=191), nullable=False),
        sa.Column('value', sa.Text(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('key', name='uq_system_config_key'),
    )
    op.create_table(
        'user',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('nickname', sa.VARCHAR(length=50), nullable=False),
        sa.Column('avatar', sa.VARCHAR(length=255), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_table(
        'user_config',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('settings', sa.JSON(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_table(
        'user_subscription',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('subscription_id', sa.Integer(), nullable=False),
        sa.Column('is_deleted', sa.Boolean(), nullable=False),
        sa.Column('is_nsfw', sa.Boolean(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('user_id', 'subscription_id', name='uix_user_subscription'),
    )
    op.create_index('ix_user_subscription_is_deleted', 'user_subscription', ['is_deleted'], unique=False)
    op.create_index('ix_user_subscription_subscription_id', 'user_subscription', ['subscription_id'], unique=False)
    op.create_index('ix_user_subscription_user_id', 'user_subscription', ['user_id'], unique=False)
    op.create_table(
        'video',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('title', sa.VARCHAR(length=512), nullable=False),
        sa.Column('url', sa.VARCHAR(length=2048), nullable=False),
        sa.Column('description', sa.Text(), nullable=True),
        sa.Column('duration', sa.Integer(), nullable=True),
        sa.Column('thumbnail', sa.VARCHAR(length=2048), nullable=True),
        sa.Column('publish_date', sa.DateTime(), nullable=True),
        sa.Column('is_deleted', sa.Boolean(), nullable=False),
        sa.Column('extra_data', sa.JSON(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index('ix_video_deleted_publish_date', 'video', ['is_deleted', 'publish_date'], unique=False)
    op.create_index('ix_video_title', 'video', ['title'], unique=False)
    op.create_table(
        'video_creator',
        sa.Column('video_id', sa.Integer(), nullable=False),
        sa.Column('creator_id', sa.Integer(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint('video_id', 'creator_id'),
    )
    op.create_table(
        'video_history',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('video_id', sa.Integer(), nullable=False),
        sa.Column('start_time', sa.DateTime(), nullable=False),
        sa.Column('end_time', sa.DateTime(), nullable=False),
        sa.Column('duration', sa.Float(), nullable=False),
        sa.Column('watch_duration', sa.Integer(), nullable=False),
        sa.Column('last_position', sa.Float(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(op.f('ix_video_history_user_id'), 'video_history', ['user_id'], unique=False)
    op.create_index('ix_video_history_user_video', 'video_history', ['user_id', 'video_id'], unique=False)
    op.create_index('ix_video_history_video_id', 'video_history', ['video_id'], unique=False)
    op.create_table(
        'video_interaction',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('video_id', sa.Integer(), nullable=False),
        sa.Column('interaction_type', sa.Integer(), nullable=False, comment='1: like, 2: dislike'),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index('ix_video_interaction_user_video', 'video_interaction', ['user_id', 'video_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_video_interaction_user_video', table_name='video_interaction')
    op.drop_table('video_interaction')
    op.drop_index('ix_video_history_video_id', table_name='video_history')
    op.drop_index('ix_video_history_user_video', table_name='video_history')
    op.drop_index(op.f('ix_video_history_user_id'), table_name='video_history')
    op.drop_table('video_history')
    op.drop_table('video_creator')
    op.drop_index('ix_video_title', table_name='video')
    op.drop_index('ix_video_deleted_publish_date', table_name='video')
    op.drop_table('video')
    op.drop_index('ix_user_subscription_user_id', table_name='user_subscription')
    op.drop_index('ix_user_subscription_subscription_id', table_name='user_subscription')
    op.drop_index('ix_user_subscription_is_deleted', table_name='user_subscription')
    op.drop_table('user_subscription')
    op.drop_table('user_config')
    op.drop_table('user')
    op.drop_table('system_config')
    op.drop_index('ix_subscription_video_video_id', table_name='subscription_video')
    op.drop_index('ix_subscription_video_subscription_id', table_name='subscription_video')
    op.drop_table('subscription_video')
    op.drop_index('ix_subscription_type', table_name='subscription')
    op.drop_index('ix_subscription_is_deleted', table_name='subscription')
    op.drop_table('subscription')
    op.drop_table('podcast_subscriptions')
    op.drop_table('podcast_play_history')
    op.drop_index(op.f('ix_podcast_episodes_title'), table_name='podcast_episodes')
    op.drop_table('podcast_episodes')
    op.drop_index(op.f('ix_podcast_channels_title'), table_name='podcast_channels')
    op.drop_table('podcast_channels')
    op.drop_table('message')
    op.drop_table('external_request_log')
    op.drop_table('download_task')
    op.drop_table('creator')
    op.drop_table('account')
    # ### end Alembic commands ###
