"""remove unnecessary column

Revision ID: 8ab109f85277
Revises: 4d7591a3502c
Create Date: 2025-01-01 12:53:09.277308

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8ab109f85277'
down_revision = '4d7591a3502c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('subscription_video_ibfk_1', 'subscription_video', type_='foreignkey')
    op.drop_constraint('subscription_video_ibfk_2', 'subscription_video', type_='foreignkey')
    op.drop_constraint('video_creator_ibfk_1', 'video_creator', type_='foreignkey')
    op.drop_constraint('video_creator_ibfk_2', 'video_creator', type_='foreignkey')
    op.drop_column('creator', 'creator_name')
    op.drop_column('creator', 'creator_id')
    op.add_column('message', sa.Column('id', sa.Integer(), nullable=False))
    op.drop_column('message', 'message_id')
    op.add_column('subscription', sa.Column('id', sa.Integer(), nullable=False))
    op.drop_column('subscription', 'subscription_id')
    op.add_column('video', sa.Column('id', sa.Integer(), nullable=False))
    op.add_column('video', sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('video', sa.Column('url', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('video', sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('video', sa.Column('duration', sa.Integer(), nullable=True))
    op.add_column('video', sa.Column('thumbnail', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.drop_index('video_url', table_name='video')
    op.create_unique_constraint(None, 'video', ['url'])
    op.drop_column('video', 'video_id')
    op.drop_column('video', 'video_description')
    op.drop_column('video', 'video_url')
    op.drop_column('video', 'video_title')
    op.drop_column('video', 'thumbnail_url')
    op.drop_column('video', 'video_duration')
    op.drop_index('idx_video_history_video', table_name='video_history')
    op.create_index('idx_video_history_video', 'video_history', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_video_history_video', table_name='video_history')
    op.create_index('idx_video_history_video', 'video_history', ['video_id'], unique=False)
    op.create_foreign_key('video_creator_ibfk_2', 'video_creator', 'video', ['video_id'], ['video_id'])
    op.create_foreign_key('video_creator_ibfk_1', 'video_creator', 'creator', ['creator_id'], ['creator_id'])
    op.add_column('video', sa.Column('video_duration', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('video', sa.Column('thumbnail_url', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=True))
    op.add_column('video', sa.Column('video_title', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=False))
    op.add_column('video', sa.Column('video_url', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=False))
    op.add_column('video', sa.Column('video_description', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=True))
    op.add_column('video', sa.Column('video_id', mysql.INTEGER(), autoincrement=True, nullable=False))
    op.drop_constraint(None, 'video', type_='unique')
    op.create_index('video_url', 'video', ['video_url'], unique=True)
    op.drop_column('video', 'thumbnail')
    op.drop_column('video', 'duration')
    op.drop_column('video', 'description')
    op.drop_column('video', 'url')
    op.drop_column('video', 'title')
    op.drop_column('video', 'id')
    op.create_foreign_key('subscription_video_ibfk_2', 'subscription_video', 'video', ['video_id'], ['video_id'])
    op.create_foreign_key('subscription_video_ibfk_1', 'subscription_video', 'subscription', ['subscription_id'], ['subscription_id'])
    op.add_column('subscription', sa.Column('subscription_id', mysql.INTEGER(), autoincrement=True, nullable=False))
    op.drop_column('subscription', 'id')
    op.add_column('message', sa.Column('message_id', mysql.INTEGER(), autoincrement=True, nullable=False))
    op.drop_column('message', 'id')
    op.add_column('creator', sa.Column('creator_id', mysql.INTEGER(), autoincrement=True, nullable=False))
    op.add_column('creator', sa.Column('creator_name', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=False))
    # ### end Alembic commands ###
