"""add_message_tracking_fields

Revision ID: 90d45eacb1bb
Revises: 91699cf62760
Create Date: 2025-10-03 16:08:49.438144

"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = '90d45eacb1bb'
down_revision = '91699cf62760'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('message', sa.Column('trace_id', sa.VARCHAR(length=64), nullable=True))
    op.add_column('message', sa.Column('queue_name', sa.VARCHAR(length=128), nullable=True))
    op.add_column('message', sa.Column('message_type', sa.VARCHAR(length=64), nullable=True))
    op.add_column('message', sa.Column('status', sa.VARCHAR(length=32), nullable=False))
    op.add_column('message', sa.Column('error_msg', sa.Text(), nullable=True))
    op.add_column('message', sa.Column('processed_at', sa.DateTime(), nullable=True))
    op.create_index('ix_message_created_at', 'message', ['created_at'], unique=False)
    op.create_index('ix_message_queue_name', 'message', ['queue_name'], unique=False)
    op.create_index('ix_message_status', 'message', ['status'], unique=False)
    op.create_index('ix_message_trace_id', 'message', ['trace_id'], unique=False)
    op.drop_column('message', 'send_status')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('message', sa.Column('send_status', sa.VARCHAR(length=32), autoincrement=False, nullable=False))
    op.drop_index('ix_message_trace_id', table_name='message')
    op.drop_index('ix_message_status', table_name='message')
    op.drop_index('ix_message_queue_name', table_name='message')
    op.drop_index('ix_message_created_at', table_name='message')
    op.drop_column('message', 'processed_at')
    op.drop_column('message', 'error_msg')
    op.drop_column('message', 'status')
    op.drop_column('message', 'message_type')
    op.drop_column('message', 'queue_name')
    op.drop_column('message', 'trace_id')
    # ### end Alembic commands ###
