"""drop poadcast tables

Revision ID: 91699cf62760
Revises: a89b6e17eb6c
Create Date: 2025-10-03 13:55:41.860833

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '91699cf62760'
down_revision = 'a89b6e17eb6c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_podcast_channels_title'), table_name='podcast_channels')
    op.drop_table('podcast_channels')
    op.drop_table('podcast_subscriptions')
    op.drop_index(op.f('ix_podcast_episodes_title'), table_name='podcast_episodes')
    op.drop_table('podcast_episodes')
    op.drop_table('podcast_play_history')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('podcast_play_history',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('episode_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('position', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('duration', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('last_played_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('is_finished', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('podcast_play_history_pkey'))
    )
    op.create_table('podcast_episodes',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('channel_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(length=128), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('audio_url', sa.VARCHAR(length=2048), autoincrement=False, nullable=False),
    sa.Column('duration', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('published_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('cover_url', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.Column('is_read', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('last_position', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('podcast_episodes_pkey'))
    )
    op.create_index(op.f('ix_podcast_episodes_title'), 'podcast_episodes', ['title'], unique=False)
    op.create_table('podcast_subscriptions',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('channel_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('podcast_subscriptions_pkey'))
    )
    op.create_table('podcast_channels',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('title', sa.VARCHAR(length=128), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('author', sa.VARCHAR(length=128), autoincrement=False, nullable=True),
    sa.Column('cover_url', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.Column('rss_url', sa.VARCHAR(length=2048), autoincrement=False, nullable=False),
    sa.Column('website_url', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.Column('language', sa.VARCHAR(length=32), autoincrement=False, nullable=True),
    sa.Column('categories', sa.VARCHAR(length=32), autoincrement=False, nullable=True),
    sa.Column('last_updated', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('podcast_channels_pkey'))
    )
    op.create_index(op.f('ix_podcast_channels_title'), 'podcast_channels', ['title'], unique=False)
    # ### end Alembic commands ###
