"""add video_interaction table

Revision ID: 9313ee0fab95
Revises: 26a66d226ef6
Create Date: 2025-03-02 00:46:49.229868

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9313ee0fab95'
down_revision = '26a66d226ef6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('video_interaction',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('video_id', sa.Integer(), nullable=False),
    sa.Column('interaction_type', sa.Integer(), nullable=False, comment='1: like, 2: dislike'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_video_interaction_user_video', 'video_interaction', ['user_id', 'video_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_video_interaction_user_video', table_name='video_interaction')
    op.drop_table('video_interaction')
    # ### end Alembic commands ###
