"""add_indexes_for_count_query_optimization

Revision ID: 979c773ed34a
Revises: 6f204e073323
Create Date: 2025-10-05 10:21:44.421685

"""
from alembic import op

# revision identifiers, used by Alembic.
revision = "979c773ed34a"
down_revision = "6f204e073323"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index("ix_subscription_deleted_id", "subscription", ["is_deleted", "id"], unique=False)
    op.create_index("ix_user_subscription_sub_user_deleted", "user_subscription", ["subscription_id", "user_id", "is_deleted"], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_user_subscription_sub_user_deleted", table_name="user_subscription")
    op.drop_index("ix_subscription_deleted_id", table_name="subscription")
    # ### end Alembic commands ###
