"""add_scheduled_task_table

Revision ID: a6af4b319ee1
Revises: ba7cd570c8b0
Create Date: 2026-01-03 20:23:12.821532

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a6af4b319ee1'
down_revision = 'ba7cd570c8b0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scheduled_task',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), nullable=False, comment='任务名称'),
    sa.Column('task_type', sa.VARCHAR(length=20), nullable=False, comment='任务类型'),
    sa.Column('description', sa.TEXT(), nullable=True, comment='任务描述'),
    sa.Column('interval', sa.Integer(), nullable=False, comment='执行间隔数值'),
    sa.Column('unit', sa.VARCHAR(length=20), nullable=False, comment='时间单位'),
    sa.Column('start_immediately', sa.Boolean(), nullable=False, comment='是否立即执行'),
    sa.Column('max_retries', sa.Integer(), nullable=False, comment='最大重试次数'),
    sa.Column('status', sa.VARCHAR(length=20), nullable=False, comment='任务状态'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='是否激活'),
    sa.Column('task_class', sa.VARCHAR(length=255), nullable=False, comment='任务类名'),
    sa.Column('task_params', sa.JSON(), nullable=False, comment='任务参数'),
    sa.Column('last_run_at', sa.DateTime(), nullable=True, comment='最后执行时间'),
    sa.Column('next_run_at', sa.DateTime(), nullable=True, comment='下次执行时间'),
    sa.Column('last_error', sa.TEXT(), nullable=True, comment='最后错误信息'),
    sa.Column('run_count', sa.Integer(), nullable=False, comment='执行次数'),
    sa.Column('success_count', sa.Integer(), nullable=False, comment='成功次数'),
    sa.Column('error_count', sa.Integer(), nullable=False, comment='失败次数'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.VARCHAR(length=100), nullable=True, comment='创建者'),
    sa.Column('updated_by', sa.VARCHAR(length=100), nullable=True, comment='更新者'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('task_execution_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False, comment='任务ID'),
    sa.Column('task_name', sa.VARCHAR(length=100), nullable=False, comment='任务名称'),
    sa.Column('started_at', sa.DateTime(), nullable=False, comment='开始时间'),
    sa.Column('finished_at', sa.DateTime(), nullable=True, comment='完成时间'),
    sa.Column('duration', sa.Integer(), nullable=True, comment='执行时长(毫秒)'),
    sa.Column('status', sa.VARCHAR(length=20), nullable=False, comment='执行状态'),
    sa.Column('error_message', sa.TEXT(), nullable=True, comment='错误信息'),
    sa.Column('result_data', sa.JSON(), nullable=True, comment='执行结果数据'),
    sa.Column('executed_by', sa.VARCHAR(length=100), nullable=True, comment='执行者'),
    sa.Column('trace_id', sa.VARCHAR(length=100), nullable=True, comment='链路追踪ID'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('task_execution_log')
    op.drop_table('scheduled_task')
    # ### end Alembic commands ###
