"""add index for video_history end_time

Revision ID: a89b6e17eb6c
Revises: 7a101523feb2
Create Date: 2025-10-03 13:16:57.214535

"""
from alembic import op

# revision identifiers, used by Alembic.
revision = "a89b6e17eb6c"
down_revision = "7a101523feb2"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index("ix_video_history_user_end_time", "video_history", ["user_id", "end_time"], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_video_history_user_end_time", table_name="video_history")
    # ### end Alembic commands ###
