"""add_vip_video_record_table

Revision ID: ba7cd570c8b0
Revises: 25928e33059b
Create Date: 2026-01-03 16:00:23.367856

"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = 'ba7cd570c8b0'
down_revision = '25928e33059b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'vip_video_record',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('url', sa.VARCHAR(length=2048), nullable=False),
        sa.Column('site', sa.VARCHAR(length=128), nullable=False),
        sa.Column('error_message', sa.Text(), nullable=True),
        sa.Column('error_type', sa.VARCHAR(length=128), nullable=True),
        sa.Column('retry_count', sa.Integer(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index('ix_vip_video_created_at', 'vip_video_record', ['created_at'], unique=False)
    op.create_index('ix_vip_video_site', 'vip_video_record', ['site'], unique=False)
    op.create_index('ix_vip_video_url', 'vip_video_record', ['url'], unique=False)
    op.create_index('ux_vip_video_url_unique', 'vip_video_record', ['url'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ux_vip_video_url_unique', table_name='vip_video_record')
    op.drop_index('ix_vip_video_url', table_name='vip_video_record')
    op.drop_index('ix_vip_video_site', table_name='vip_video_record')
    op.drop_index('ix_vip_video_created_at', table_name='vip_video_record')
    op.drop_table('vip_video_record')
    # ### end Alembic commands ###
