"""change sqlmodel to sqlalchemy

Revision ID: bfc975377fe7
Revises: 
Create Date: 2025-01-01 16:37:45.143034

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'bfc975377fe7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('creator',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=128), nullable=True),
    sa.Column('url', sa.VARCHAR(length=2048), nullable=False),
    sa.Column('avatar', sa.VARCHAR(length=2048), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('extra_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('download_task',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('video_id', sa.Integer(), nullable=False),
    sa.Column('status', mysql.VARCHAR(length=32), nullable=False),
    sa.Column('downloaded_size', sa.BigInteger(), nullable=True),
    sa.Column('total_size', sa.BigInteger(), nullable=True),
    sa.Column('speed', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('eta', mysql.VARCHAR(length=32), nullable=True),
    sa.Column('percent', mysql.VARCHAR(length=32), nullable=True),
    sa.Column('retry', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('message',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('send_status', sa.VARCHAR(length=32), nullable=False),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('next_retry_time', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('podcast_channels',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.VARCHAR(length=128), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('author', sa.VARCHAR(length=128), nullable=True),
    sa.Column('cover_url', sa.VARCHAR(length=2048), nullable=True),
    sa.Column('rss_url', sa.VARCHAR(length=2048), nullable=False),
    sa.Column('website_url', sa.VARCHAR(length=2048), nullable=True),
    sa.Column('language', sa.VARCHAR(length=32), nullable=True),
    sa.Column('categories', sa.VARCHAR(length=32), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_podcast_channels_title'), 'podcast_channels', ['title'], unique=False)
    op.create_table('podcast_episodes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('channel_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.VARCHAR(length=128), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('audio_url', sa.VARCHAR(length=2048), nullable=False),
    sa.Column('duration', sa.Integer(), nullable=True),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('cover_url', sa.VARCHAR(length=2048), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('last_position', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_podcast_episodes_title'), 'podcast_episodes', ['title'], unique=False)
    op.create_table('podcast_play_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('episode_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('duration', sa.Integer(), nullable=False),
    sa.Column('last_played_at', sa.DateTime(), nullable=False),
    sa.Column('is_finished', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('podcast_subscriptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('channel_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('subscription',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content_type', sa.VARCHAR(length=32), nullable=False),
    sa.Column('content_name', sa.VARCHAR(length=128), nullable=False),
    sa.Column('content_url', sa.VARCHAR(length=2048), nullable=True),
    sa.Column('avatar_url', sa.VARCHAR(length=2048), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('total_videos', sa.Integer(), nullable=False),
    sa.Column('is_enable', sa.Boolean(), nullable=False),
    sa.Column('is_auto_download', sa.Boolean(), nullable=False),
    sa.Column('is_download_all', sa.Boolean(), nullable=False),
    sa.Column('is_extract_all', sa.Boolean(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('extra_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('subscription_video',
    sa.Column('subscription_id', sa.Integer(), nullable=False),
    sa.Column('video_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('subscription_id', 'video_id')
    )
    op.create_table('video',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.VARCHAR(length=128), nullable=False),
    sa.Column('url', sa.VARCHAR(length=2048), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('duration', sa.Integer(), nullable=True),
    sa.Column('thumbnail', sa.VARCHAR(length=2048), nullable=True),
    sa.Column('publish_date', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('extra_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('video_creator',
    sa.Column('video_id', sa.Integer(), nullable=False),
    sa.Column('creator_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('video_id', 'creator_id')
    )
    op.create_table('video_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('video_id', sa.Integer(), nullable=False),
    sa.Column('watch_duration', sa.Integer(), nullable=False),
    sa.Column('last_position', sa.Integer(), nullable=False),
    sa.Column('total_duration', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('video_history')
    op.drop_table('video_creator')
    op.drop_table('video')
    op.drop_table('subscription_video')
    op.drop_table('subscription')
    op.drop_table('podcast_subscriptions')
    op.drop_table('podcast_play_history')
    op.drop_index(op.f('ix_podcast_episodes_title'), table_name='podcast_episodes')
    op.drop_table('podcast_episodes')
    op.drop_index(op.f('ix_podcast_channels_title'), table_name='podcast_channels')
    op.drop_table('podcast_channels')
    op.drop_table('message')
    op.drop_table('download_task')
    op.drop_table('creator')
    # ### end Alembic commands ###
