"""add video domain and search indexes

Revision ID: c16114e79cd2
Revises: f755ccf075b6
Create Date: 2026-01-19 00:18:14.777750

"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = 'c16114e79cd2'
down_revision = 'f755ccf075b6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('video', sa.Column('domain', sa.VARCHAR(length=255), nullable=True))
    op.create_index('ix_video_domain', 'video', ['domain'], unique=False)

    op.execute('CREATE EXTENSION IF NOT EXISTS pg_trgm')
    op.create_index(
        'ix_video_title_trgm',
        'video',
        ['title'],
        unique=False,
        postgresql_using='gin',
        postgresql_ops={'title': 'gin_trgm_ops'},
    )

    op.execute(
        """
        UPDATE video
        SET domain = v.normalized_domain
        FROM (
            SELECT
                id,
                CASE
                    WHEN host ~ '^[0-9.]+$' THEN host
                    WHEN array_length(parts, 1) >= 2 THEN
                        parts[array_length(parts, 1) - 1] || '.' || parts[array_length(parts, 1)]
                    ELSE host
                END AS normalized_domain
            FROM (
                SELECT
                    id,
                    split_part(
                        regexp_replace(regexp_replace(url, '^https?://', ''), '/.*$', ''),
                        ':',
                        1
                    ) AS host,
                    string_to_array(
                        split_part(
                            regexp_replace(regexp_replace(url, '^https?://', ''), '/.*$', ''),
                            ':',
                            1
                        ),
                        '.'
                    ) AS parts
                FROM video
                WHERE url IS NOT NULL AND url <> ''
            ) AS derived
        ) AS v
        WHERE video.id = v.id AND video.domain IS NULL
        """,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_video_title_trgm', table_name='video', postgresql_using='gin')
    op.drop_index('ix_video_domain', table_name='video')
    op.drop_column('video', 'domain')
    # ### end Alembic commands ###
