"""drop external request log table column response

Revision ID: cda27c5492f6
Revises: 260dbc62d518
Create Date: 2025-01-24 02:01:03.948333

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'cda27c5492f6'
down_revision = '260dbc62d518'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('external_request_log', 'response')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('external_request_log', sa.Column('response', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=True))
    # ### end Alembic commands ###
