"""add performance indexes for video list query

Revision ID: d20b9a4d9bdd
Revises: e63fab4b8fa9
Create Date: 2025-10-04 22:23:23.935844

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd20b9a4d9bdd'
down_revision = 'e63fab4b8fa9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_user_subscription_user_deleted_nsfw', 'user_subscription', ['user_id', 'is_deleted', 'is_nsfw'], unique=False)
    op.create_index('ix_video_deleted_created_at', 'video', ['is_deleted', 'created_at'], unique=False)
    op.create_index('ix_video_interaction_user_type_video', 'video_interaction', ['user_id', 'interaction_type', 'video_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_video_interaction_user_type_video', table_name='video_interaction')
    op.drop_index('ix_video_deleted_created_at', table_name='video')
    op.drop_index('ix_user_subscription_user_deleted_nsfw', table_name='user_subscription')
    # ### end Alembic commands ###
