"""initial_schema

Revision ID: d87e0a7a650a
Revises: 
Create Date: 2024-11-10 12:01:02.550624

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd87e0a7a650a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('channel',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('channel_id', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('name', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('url', mysql.VARCHAR(length=1024), nullable=False),
    sa.Column('avatar', mysql.VARCHAR(length=2048), nullable=False),
    sa.Column('total_videos', sa.Integer(), nullable=False),
    sa.Column('if_enable', sa.Boolean(), nullable=True),
    sa.Column('if_auto_download', sa.Boolean(), nullable=True),
    sa.Column('if_download_all', sa.Boolean(), nullable=True),
    sa.Column('if_extract_all', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_channel_updated_at'), 'channel', ['updated_at'], unique=False)
    op.create_table('channel_video',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('channel_id', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('channel_name', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('channel_avatar', mysql.VARCHAR(length=2048), nullable=False),
    sa.Column('title', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('video_id', mysql.VARCHAR(length=64), nullable=False),
    sa.Column('domain', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('url', mysql.VARCHAR(length=1024), nullable=False),
    sa.Column('thumbnail', mysql.VARCHAR(length=2048), nullable=True),
    sa.Column('duration', sa.Integer(), nullable=True),
    sa.Column('if_read', sa.Boolean(), nullable=True),
    sa.Column('if_downloaded', sa.Boolean(), nullable=True),
    sa.Column('is_disliked', sa.Boolean(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_channel_video_updated_at'), 'channel_video', ['updated_at'], unique=False)
    op.create_table('download_task',
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('url', mysql.VARCHAR(length=2048), nullable=False),
    sa.Column('thumbnail', mysql.VARCHAR(length=2048), nullable=True),
    sa.Column('domain', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('video_id', mysql.VARCHAR(length=64), nullable=False),
    sa.Column('channel_id', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('channel_name', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('channel_url', mysql.VARCHAR(length=2048), nullable=True),
    sa.Column('channel_avatar', mysql.VARCHAR(length=2048), nullable=True),
    sa.Column('title', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('status', mysql.VARCHAR(length=32), nullable=False),
    sa.Column('downloaded_size', sa.BigInteger(), nullable=True),
    sa.Column('total_size', sa.BigInteger(), nullable=True),
    sa.Column('speed', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('eta', mysql.VARCHAR(length=32), nullable=True),
    sa.Column('percent', mysql.VARCHAR(length=32), nullable=True),
    sa.Column('retry', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('task_id')
    )
    op.create_index(op.f('ix_download_task_updated_at'), 'download_task', ['updated_at'], unique=False)
    op.create_table('message',
    sa.Column('message_id', sa.Integer(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('send_status', sa.VARCHAR(length=32), nullable=False),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('next_retry_time', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('message_id')
    )
    op.create_index(op.f('ix_message_updated_at'), 'message', ['updated_at'], unique=False)
    op.create_table('video_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('video_id', sa.String(length=255), nullable=False),
    sa.Column('channel_id', sa.String(length=255), nullable=False),
    sa.Column('watch_duration', sa.Integer(), nullable=True),
    sa.Column('last_position', sa.Integer(), nullable=True),
    sa.Column('total_duration', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_video_history_updated', 'video_history', ['updated_at'], unique=False)
    op.create_index('idx_video_history_video', 'video_history', ['video_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_video_history_video', table_name='video_history')
    op.drop_index('idx_video_history_updated', table_name='video_history')
    op.drop_table('video_history')
    op.drop_index(op.f('ix_message_updated_at'), table_name='message')
    op.drop_table('message')
    op.drop_index(op.f('ix_download_task_updated_at'), table_name='download_task')
    op.drop_table('download_task')
    op.drop_index(op.f('ix_channel_video_updated_at'), table_name='channel_video')
    op.drop_table('channel_video')
    op.drop_index(op.f('ix_channel_updated_at'), table_name='channel')
    op.drop_table('channel')
    # ### end Alembic commands ###
