"""add_progress_record_table

Revision ID: e63fab4b8fa9
Revises: 90d45eacb1bb
Create Date: 2025-10-04 09:55:07.376368

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e63fab4b8fa9'
down_revision = '90d45eacb1bb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('progress_record',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_type', mysql.VARCHAR(length=64), nullable=False),
    sa.Column('trace_id', mysql.VARCHAR(length=64), nullable=True),
    sa.Column('subscription_id', sa.Integer(), nullable=True),
    sa.Column('video_id', sa.Integer(), nullable=True),
    sa.Column('url', mysql.VARCHAR(length=2048), nullable=True),
    sa.Column('current_count', sa.Integer(), nullable=False),
    sa.Column('total_count', sa.Integer(), nullable=False),
    sa.Column('progress_percentage', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('message', mysql.VARCHAR(length=512), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_progress_created_at', 'progress_record', ['created_at'], unique=False)
    op.create_index('ix_progress_event_type', 'progress_record', ['event_type'], unique=False)
    op.create_index('ix_progress_subscription_id', 'progress_record', ['subscription_id'], unique=False)
    op.create_index('ix_progress_trace_id', 'progress_record', ['trace_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_progress_trace_id', table_name='progress_record')
    op.drop_index('ix_progress_subscription_id', table_name='progress_record')
    op.drop_index('ix_progress_event_type', table_name='progress_record')
    op.drop_index('ix_progress_created_at', table_name='progress_record')
    op.drop_table('progress_record')
    # ### end Alembic commands ###
