"""add video index

Revision ID: e92290a12e6e
Revises: 4b6c5ebeb483
Create Date: 2025-08-05 20:50:39.521303

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e92290a12e6e'
down_revision = '4b6c5ebeb483'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_video_is_deleted', table_name='video')
    op.drop_index('ix_video_publish_date', table_name='video')
    op.create_index('ix_video_deleted_publish_date', 'video', ['is_deleted', 'publish_date'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_video_deleted_publish_date', table_name='video')
    op.create_index('ix_video_publish_date', 'video', ['publish_date'], unique=False)
    op.create_index('ix_video_is_deleted', 'video', ['is_deleted'], unique=False)
    # ### end Alembic commands ###
