"""alter table subscription add column total_videos

Revision ID: f17f5d39b5ef
Revises: 5e778148978b
Create Date: 2024-12-22 16:29:31.273866

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = 'f17f5d39b5ef'
down_revision = '5e778148978b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscription', sa.Column('total_videos', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subscription', 'total_videos')
    # ### end Alembic commands ###
