"""add_legacy_tasks_column

Revision ID: f755ccf075b6
Revises: 41788451930b
Create Date: 2026-01-03 21:17:01.670061

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "f755ccf075b6"
down_revision = "41788451930b"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "scheduler_status",
        sa.Column("legacy_tasks", sa.JSON(), nullable=False, server_default="{}", comment="传统任务信息"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("scheduler_status", "legacy_tasks")
    # ### end Alembic commands ###
