"""remove user subscirption is_auto_download column

Revision ID: ff3013bba0d5
Revises: 349698b1daa9
Create Date: 2025-02-05 20:22:06.773638

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ff3013bba0d5'
down_revision = '349698b1daa9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subscription', 'is_enable')
    op.drop_column('user_subscription', 'is_enable')
    op.drop_column('user_subscription', 'is_auto_download')
    op.drop_column('user_subscription', 'is_download_all')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_subscription', sa.Column('is_download_all', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False))
    op.add_column('user_subscription', sa.Column('is_auto_download', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False))
    op.add_column('user_subscription', sa.Column('is_enable', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False))
    op.add_column('subscription', sa.Column('is_enable', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
